### ISSUE TITLE
What is the tree_depth and cascade_depth of sp_human_face_17_for_mobile.dat?

### ISSUE THREAD

**Issue by Abdul-Mukit** [EnoxSoftware/DlibFaceLandmarkDetector#11]
I need to train a custom shape predictor model like "sp_human_face_17_for_mobile.dat". I need to know the training parameters used for training the model so that I can achieve similar performance on the Hololens. Especially I need to know the tree depth and cascade_depth. Any comment would be very helpful.

**Comment by EnoxSoftware** [comment]
For details of the training data set, please refer to "DlibFaceLandmarkDetector/DlibFaceLandmarkDetectorTrainingDataset.txt".

**Comment by Abdul-Mukit** [comment]
Got it, thank you.
