### ISSUE TITLE
Loading svm file

### ISSUE THREAD

**Issue by apapaxiong** [EnoxSoftware/DlibFaceLandmarkDetector#3]
Is there a way to load .svm file generated by Dlib?

**Comment by EnoxSoftware** [comment]
Please set your .svm file to objectDetectorFilePath.

http://enoxsoftware.github.io/DlibFaceLandmarkDetector/doc/html/class_dlib_face_landmark_detector_1_1_face_landmark_detector.html#af719ebca6f440b5c3d091095aa3adae3
DlibFaceLandmarkDetector.FaceLandmarkDetector.FaceLandmarkDetector	(	string 	objectDetectorFilePath,
string 	shapePredictorFilePath 
)
