### ISSUE TITLE
Does the constructor parameter of FaceLandmarkDetector not support Chinese character path?

### ISSUE THREAD

**Issue by huihut** [EnoxSoftware/DlibFaceLandmarkDetector#8]
In the `FaceLandmarkDetector.cs`
```cs
if (!DlibFaceLandmarkDetector_LoadShapePredictor (nativeObj, shapePredictorFilePath)) {
    Debug.LogError ("Failed to load " + shapePredictorFilePath);
}
```

shapePredictorFilePath = "D:/code/git/测试test/Assets/StreamingAssets\\sp_human_face_68.dat"

Failed to load D:/code/git/测试test/Assets/StreamingAssets\sp_human_face_68.dat

I want it to run in the path of Chinese characters, what should I do?

**Comment by EnoxSoftware** [comment]
Please enable the "Use Unicode UTF-8 for worldwide language support" setting
.All Settings -> Time & Language -> Language -> "Administrative Language Settings"
![UnicodeSetting](https://user-images.githubusercontent.com/7920392/66835662-e48da180-ef9a-11e9-803d-468b09eae33d.png)

**Comment by huihut** [comment]
This can solve my computer problem, but the program written with DlibFaceLandmarkDetector will run on the user's computer (including Win7, MacOS).

Is it better to have the `DlibFaceLandmarkDetector_LoadShapePredictor` interface of `dlibfacelandmarkdetector.dll` receive the UTF-8 character `shapePredictorFilename`?

**Comment by EnoxSoftware** [comment]
You can set the relative file path from the project folder.

            //dlibShapePredictorFilePath = Utils.getFilePath (dlibShapePredictorFileName);
            dlibShapePredictorFilePath = "./Assets/StreamingAssets/sp_human_face_68.dat";

**Comment by huihut** [comment]
Thank you very much, I solved it.

```cs
#if UNITY_WEBGL && !UNITY_EDITOR
            var getFilePath_Coroutine = DlibFaceLandmarkDetector.Utils.getFilePathAsync (dlibShapePredictorMobileFileName, (result) => {
                coroutines.Clear ();

                dlibShapePredictorFilePath = result;
                Run ();
            });
            coroutines.Push (getFilePath_Coroutine);
            StartCoroutine (getFilePath_Coroutine);
#else
#if UNITY_EDITOR
            dlibShapePredictorFilePath = "./Assets/StreamingAssets/sp_human_face_68.dat";
#elif UNITY_STANDALONE_WIN
            dlibShapePredictorFilePath = "./Avalive_Data/StreamingAssets/sp_human_face_68.dat";
#elif UNITY_ANDROID || UNITY_IOS
            dlibShapePredictorFilePath = DlibFaceLandmarkDetector.Utils.getFilePath (dlibShapePredictorMobileFileName);
#else
            dlibShapePredictorFilePath = DlibFaceLandmarkDetector.Utils.getFilePath (dlibShapePredictorFileName);
#endif
            Run();
#endif
```
